version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: billmate-db
    environment:
      POSTGRES_DB: billmate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend 
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  # redis:
  #   image: redis:7.4.2-alpine
  #   restart: unless-stopped
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   command: redis-server --save 60 1 --loglevel warning

  # redis-commander:
  #   container_name: redis-commander
  #   hostname: redis-commander
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #   - REDIS_HOST=redis
  #   ports:
  #     - "127.0.0.1:8081:8081"
  #   depends_on:
  #     - redis
  #   restart:
  #     unless-stopped
  
volumes:
  db-data:

networks:
  backend:
    driver: bridge